library(dplyr)
library(tidyr)
foldername <- "UCI HAR Dataset"
allfeatures<-read.table(file.path(foldername, "features.txt"), stringsAsFactors = FALSE, col.names = c("lineNum","featureName"))
featuresIdx <- grep("-mean\\(\\)|-std\\(\\)", allfeatures[,2])
features <- allfeatures[featuresIdx, 2]
features <- gsub("-mean\\(\\)", "Mean", features)
features <- gsub("-std\\(\\)","Std", features)
labels <-read.table(file.path(foldername, "activity_labels.txt"))
xtest<-tbl_df(read.table(file.path(foldername, "test","X_test.txt"), col.names = allfeatures[,2])[,featuresIdx])
ytest<-tbl_df(read.table(file.path(foldername, "test", "Y_test.txt"), col.names = "activity"))
stest<-tbl_df(read.table(file.path(foldername, "test", "subject_test.txt"), col.names = "subject"))
xtrain<-tbl_df(read.table(file.path(foldername, "train", "X_train.txt"), col.names = allfeatures[,2])[,featuresIdx])
ytrain<-tbl_df(read.table(file.path(foldername, "train", "y_train.txt"), col.names = "activity"))
strain<-tbl_df(read.table(file.path(foldername, "train", "subject_train.txt"), col.names = "subject"))
ucihardata <- union(tbl_df(data.frame(stest, ytest, xtest)), tbl_df(data.frame(strain, ytrain,xtrain)))
ucihardata <- mutate(ucihardata, activity=factor(activity, levels = labels[,1],labels = labels[,2]))
names(ucihardata) = c("subject","activity", features)
ucihardata <- ucihardata %>% group_by(subject, activity) %>% summarise_all(mean)
write.table(ucihardata,"ucihardata.txt", row.names = FALSE)
